<a href="https://colab.research.google.com/github/kaio147/-Bioinformatica/blob/main/fut_0_0_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score , f1_score, precision_score, recall_score
from sklearn.feature_selection import SelectKBest
from sklearn.model_selection import  GridSearchCV
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import scale

In [38]:
df = pd.read_csv('BRA.csv')
df.dropna()

     Country   League  Season        Date   Time  ...  MaxD  MaxA  AvgH  AvgD  AvgA
0     Brazil  Serie A    2012  19/05/2012  22:30  ...  3.87  5.31  1.69  3.50  4.90
1     Brazil  Serie A    2012  19/05/2012  22:30  ...  3.42  2.70  2.59  3.23  2.58
2     Brazil  Serie A    2012  20/05/2012  01:00  ...  4.05  7.22  1.59  3.67  5.64
3     Brazil  Serie A    2012  20/05/2012  20:00  ...  3.39  3.15  2.35  3.26  2.84
4     Brazil  Serie A    2012  20/05/2012  20:00  ...  3.53  4.41  1.89  3.33  3.89
...      ...      ...     ...         ...    ...  ...   ...   ...   ...   ...   ...
3481  Brazil  Serie A    2021  28/06/2021  00:30  ...  3.10  2.95  2.75  2.93  2.79
3482  Brazil  Serie A    2021  28/06/2021  00:30  ...  3.22  2.88  2.72  3.04  2.72
3483  Brazil  Serie A    2021  28/06/2021  00:30  ...  3.32  2.65  2.86  3.13  2.53
3484  Brazil  Serie A    2021  28/06/2021  00:30  ...  3.10  3.67  2.33  2.92  3.45
3485  Brazil  Serie A    2021  29/06/2021  00:00  ...  3.32  2.28  3.33  3.21  2.21

[3485 rows x 19 columns]

In [39]:
df['Res'] = df['Res'].map({'D': 0,
                             'H': 1,
                             'A':2},
                             na_action=None)

In [40]:
df.dropna(inplace=True)

In [41]:
df2 = df.drop(['Country','League','Season','Date','Time','Home','Away','HG','AG'],1)

In [42]:
df2

      Res    PH    PD    PA  MaxH  MaxD  MaxA  AvgH  AvgD  AvgA
0     0.0  1.75  3.86  5.25  1.76  3.87  5.31  1.69  3.50  4.90
1     0.0  2.83  3.39  2.68  2.83  3.42  2.70  2.59  3.23  2.58
2     1.0  1.60  4.04  6.72  1.67  4.05  7.22  1.59  3.67  5.64
3     1.0  2.49  3.35  3.15  2.49  3.39  3.15  2.35  3.26  2.84
4     2.0  1.96  3.53  4.41  1.96  3.53  4.41  1.89  3.33  3.89
...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
3481  0.0  2.84  3.01  2.87  2.85  3.10  2.95  2.75  2.93  2.79
3482  0.0  2.77  3.11  2.86  2.81  3.22  2.88  2.72  3.04  2.72
3483  1.0  3.00  3.14  2.63  3.00  3.32  2.65  2.86  3.13  2.53
3484  0.0  2.38  2.96  3.63  2.40  3.10  3.67  2.33  2.92  3.45
3485  2.0  3.53  3.27  2.25  3.60  3.32  2.28  3.33  3.21  2.21

[3485 rows x 10 columns]

In [43]:
features = df2.drop(['Res'],1)
labels = df2['Res']
x_train = features[:1161]
x_test = features[1162:2230]
x_validaÇao = features[2231:3485]
y_train = labels[:1161]
y_test = labels[1162:2230]
y_validaÇao = labels[2231:3485]

In [53]:
clf = SVC()
clf.fit(x_train, y_train)
pred= clf.predict(x_test)
pred2= clf.predict(x_validaÇao)

svc_acc = accuracy_score(y_test, pred)
svc_acc1 = accuracy_score(y_validaÇao, pred2)
f1=f1_score(y_test,pred, average='micro')
f2=f1_score(y_validaÇao,pred2, average='micro')
print ('Acurácia SVC teste :{}'.format(svc_acc))
print ('Acurácia SVC validaçao:{}'.format(svc_acc1))
print ('F1 Score teste:{}'.format(f1))
print ('F1 Score validaçao:{}'.format(f2))

Acurácia SVC teste :0.5140449438202247
Acurácia SVC validaçao:0.518341307814992
F1 Score teste:0.5140449438202247
F1 Score validaçao:0.518341307814992

In [ ]:
#Country = país do campeonato
#League = nome da liga
#game_id = id do jogo
#Season = temporada
#date = data do jogo
#Time = hora do jogo
#Home = Time da casa
#home_id = id do time da casa
#Away = time visitante
#Away_id =  id do time visitante
#HG = Gols do time da casa
#AG = Gols do time visitante
#Res = Resultado do jogo (D=Draw, H=Home win, A=Away win)
#PH = probablidade vitória time da casa provida pela Pinacle (casa de aposta inglesa)
#PD = probablidade empate provida pela Pinacle (casa de aposta inglesa)
#PA = probablidade vitória time visitante provida pela Pinacle (casa de aposta inglesa)
#MaxH = probablidade vitória time da casa provida pela OddsPortal (casa de aposta inglesa)
#MaxD = probablidade empate provida pela OddsPortal (casa de aposta inglesa)
#MaxA = probablidade vitória time visitante provida pela OddsPortal (casa de aposta ingles
#AvgH = probablidade média de vitória em casa provida pela OddsPortal (casa de aposta inglesa)
#AvgD = probablidade média de empate provida pela OddsPortal (casa de aposta inglesa)
#AvgA = probablidade média de vitória pelo time visitante provida pela OddsPortal (casa de aposta inglesa)